# This workflow demonstrates how to use workflow events and outputs the event name that triggered it.

name: 02 - Workflows Events
# Triggers: push, pull_request, schedule, workflow_dispatch
on:

  pull_request:
    branches:
      - main
  workflow_dispatch:

  
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: show the trigger
        run: |
          echo "The event that triggered this workflow is ${{ github.event_name }}"
          echo " on pull request"

    
